EMAIL_USE_TLS = True      # use port 587
# EMAIL_USE_SSL = False    # use port 465
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "sonnyrakaffo@gmail.com"
# EMAIL_HOST_PASSWORD = "shmbetaggnvgjiuy"
# EMAIL_HOST_PASSWORD = "agpxtcfzbgoaeurw"
EMAIL_HOST_PASSWORD = "ruicgcscfioettiq"
EMAIL_PORT = 587
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
